import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Tom\'s Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
