/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./public/imac_white.glb --types --transform --instance
Files: ./public/imac_white.glb [1MB] > imac_white-transformed.glb [88.12KB] (91%)
*/

// model downloaded from: https://archive3d.net/?a=download&id=bf2dc0df

import * as THREE from "three";
import React from "react";
import { useGLTF, Html, MeshReflectorMaterial } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Image from "next/image";
import top from "../../public/Frame1.png";
import githubicon from "../../public/github-mark-white.svg";
import dummy from "../../public/dummyimg.png";

type GLTFResult = GLTF & {
  nodes: {
    Box01_1: THREE.Mesh;
    Box01_2: THREE.Mesh;
  };
  materials: {
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
  };
};

useGLTF.preload("/imac.glb");

/* This component renders a monitor (taken out of the gltf model)
   It renders a custom scene into a texture and projects it onto monitors screen */
function ImacModel({ children, ...props }: { children: React.ReactNode }) {
  const { nodes, materials } = useGLTF("/imac.glb") as GLTFResult;
  return (
    <group {...props}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box01_2.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh geometry={nodes.Box01_1.geometry}>
          <MeshReflectorMaterial
            blur={[300, 30]}
            resolution={2048}
            mixBlur={1}
            mixStrength={80}
            roughness={1}
            depthScale={1.2}
            minDepthThreshold={0.4}
            maxDepthThreshold={1.4}
            color="#000000"
            metalness={0.8}
            mirror={0}
          />
          {children}
        </mesh>
      </group>
    </group>
  );
}

/* Renders a monitor with some text */
export function ScreenHtml(props: JSX.IntrinsicElements["group"]) {
  return (
    <ImacModel {...props}>
      {/* Drei's HTML component can "hide behind" canvas geometry */}
      <Html
        className="screen"
        rotation-x={Math.PI / 2.25}
        position={[0, -2.17, 13]}
        transform
        occlude
      >
        <div className="wrapper" onPointerDown={(e) => e.stopPropagation()}>
          <div className="top-image">
            <Image src={top} alt={""} />
          </div>
          <div className="item-row-container">
            <div className="item-prof">
              <div className="item-text">
                <h1>Profile</h1>
                <p>
                  ソフトウェア技術を使ってメディアエンターテインメントの体験をさらに豊かにしていくことをミッションとし、現在は業務用プロジェクターメーカーのソフトウェア開発に従事。
                </p>
                <p>
                  昨年一人旅でインドに行き結構ぼられたが、英語力には多少の自信がある。最近ジムに通い始め、ベンチプレスは60kgまで上げられるようになった。1993年大阪生まれ。
                </p>
              </div>
            </div>
            <div className="item-experiences">
              <div className="item-text">
                <h1>Experiences</h1>
              </div>
              <div className="item-row">
                <div className="item-icon-area">
                  <div className="item-icon">🏢</div>
                </div>
                <div className="item-desc">
                  <div className="item-title">
                    <h1>パナソニックコネクト株式会社</h1>
                    <p>2020.4 - 現在</p>
                  </div>
                  <div className="item-title">
                    <h2>開発中シミュレータアプリ</h2>
                    <p>2023.9 - 現在</p>
                  </div>
                  <div className="item-text">
                    <p>
                      Webベースで3DCGを活用したシミュレータアプリの開発を担当
                      <br />
                      Skills: React, Next.js, Three.js, AWS
                    </p>
                  </div>
                  <div className="item-partline" />
                  <div className="item-title">
                    <h2>プロジェクターコントロールアプリ</h2>
                    <p>2023.7 - 現在</p>
                  </div>
                  <div className="item-text">
                    <p>
                      業務用プロジェクターの機器制御やシミュレーションができるWindowsアプリの企画、設計、開発を担当
                      <br />
                      Skills: .NET, C++, Unity, C#
                    </p>
                  </div>
                  <div className="item-partline" />
                  <div className="item-title">
                    <h2>ジム向けソリューション検討</h2>
                    <p>2023.1 - 2023.12</p>
                  </div>
                  <div className="item-text">
                    <p>
                      トレーニングの動きを計測し、プロジェクターでグラフィカルにフィードバックするアプリに使うOSSの評価を実施した
                      <br />
                      Skills: Python
                    </p>
                  </div>
                  <div className="item-partline" />
                  <div className="item-title">
                    <h2>プロジェクター投影3Dシミュレータ</h2>
                    <p>2022.11 - 2023.6</p>
                  </div>
                  <div className="item-text">
                    <p>
                      業務用プロジェクター用のシミュレーションソフトウェアの新規機能の追加を担当した
                      <br />
                      Skills: Unity, C#, C++
                    </p>
                  </div>
                  <div className="item-partline" />
                  <div className="item-title">
                    <h2>デバイス遠隔操作ハブアプリ</h2>
                    <p>2022.4 - 2022.7</p>
                  </div>
                  <div className="item-text">
                    <p>
                      プロジェクターやディスプレイ、カメラなどを遠隔操作できるiOSアプリの仕様設計、実装をリードした
                      <br />
                      Skills: Swift, SwiftUI, C++
                    </p>
                  </div>
                  <div className="item-partline" />
                  <div className="item-title">
                    <h2>クラウドビデオ会議サービスのモバイルアプリ</h2>
                    <p>2020.7 - 2022.3</p>
                  </div>
                  <div className="item-text">
                    <p>
                      企業向けクラウドビデオ会議サービスのiOS/Android両OSのアプリのフロントエンド開発の設計、実装をリードした
                      <br />
                      Skills: Swift, Objective-C, Java, Kotlin, AWS EC2, WebRTC
                    </p>
                  </div>
                  {/* <div className="item-img">
                    <Image src={dummy} alt={""} />
                  </div> */}
                </div>
              </div>
              <div className="item-row">
                <div className="item-icon-area">
                  <div className="item-icon">🎓</div>
                </div>
                <div className="item-desc">
                  <div className="item-title">
                    <h1>大阪大学大学院</h1>
                    <p>2018.4 - 2020.3</p>
                  </div>
                  <div className="item-text">
                    <p>
                      <ul>
                        <li>
                          基礎工学研究科機能創成専攻のバイオイメージンググループに所属
                        </li>
                        <li>
                          研究テーマはHMDを使ったビデオシースルーシステム（現在でいうApple
                          VisionPro）
                        </li>
                        <li>
                          アイトラッキングを用いて視界映像のフォーカスを調節して現実とのインタラクションを容易にする研究に従事
                        </li>
                      </ul>
                      Skills: Unity, C#, OpenGL, C++
                      <br />
                      <a href="https://github.com/polatria/augfocus">Github</a>
                    </p>
                  </div>
                </div>
              </div>
              <div className="item-row">
                <div className="item-icon-area">
                  <div className="item-icon">🎓</div>
                </div>
                <div className="item-desc">
                  <div className="item-title">
                    <h1>大阪大学</h1>
                    <p>2013.4 - 2018.3</p>
                  </div>
                  <div className="item-text">
                    <p>
                      <ul>
                        <li>基礎工学部システム科学科生物工学コースに所属</li>
                        <li>
                          卒論は骨伝導で4chの立体音響を頭部に直接伝えるヘッドホンシステムの開発と評価
                        </li>
                      </ul>
                      Skills: Unity, C#, .NET
                      <br />
                      <a href="https://github.com/polatria/E3DAS">Github</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="item-others">
              <div className="item-text">
                <h1>Others</h1>
              </div>
              <div className="item-row">
                <div className="item-desc">
                  <div className="item-title">
                    <h2>ポートフォリオサイト</h2>
                    <p>
                      2024.3
                      <br />
                      Skills: React, Next.js, Three.js, Typescript
                      <br />
                      <a href="https://github.com/polatria/portfolio-site">
                        Gihtub
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>資格 TOEIC Listening & Reading</h2>
                    <p>
                      2024.1
                      <br />
                      <a href="https://iibc.cloudcerts.jp/viewer/cert/5aJemlWBgNAqgu68NgOA5VmIbVAVQ8JR5ypy4r49GODEXcr3KrzE3x6TDr7kPyLb">
                        855点
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>九州大学リーンスタートアップ演習</h2>
                    <p>
                      2022.9 - 2022.11
                      <br />
                      デザイン思考に基づくビジネス検討手法を学んで実践し、成果発表を行った
                      (
                      <a href="https://qrec.kyushu-u.ac.jp/news/20220604_01/">
                        参照
                      </a>
                      )
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>資格 AWS Solutions Architect - Associate</h2>
                    <p>
                      2021.10
                      <br />
                      <a href="https://www.credly.com/badges/d229167d-5765-4848-9805-c5f2c9304f01/public_url">
                        バッジ
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>社内勉強会 WebRTC</h2>
                    <p>
                      2021
                      <br />
                      <a href="https://zenn.dev/tornlch/articles/0427bc3fae8c96">
                        Zenn記事
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>社内勉強会 AWS EC2</h2>
                    <p>
                      2020
                      <br />
                      <a href="https://zenn.dev/tornlch/articles/9e263859030c0c">
                        Zenn記事
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>インターン チームラボ</h2>
                    <p>
                      2019.3
                      <br />
                      Instagram風SNSサイトを構築
                      <br />
                      Skills: PHP(Laravel), PostgreSQL, HTML, CSS
                      <br />
                      <a href="https://github.com/polatria/imgupp_teamLabSkillup">
                        Gihtub
                      </a>
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>インターン ソニー株式会社</h2>
                    <p>
                      2019.2
                      <br />
                      スマートスピーカーを題材にしたハッカソン (2位)
                      <br />
                      Skills: HTML, CSS, JavaScript
                    </p>
                  </div>
                  <div className="item-title">
                    <h2>
                      短期留学 Italian Design Summer School @ University of
                      Bologna
                    </h2>
                    <p>
                      2016.8
                      <br />
                      イタリアのボローニャ大学でプロダクトデザインの研修を受け、成果発表を行った
                      (<a href="http://italiandesign.ing.unibo.it/">参照</a>)
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="footer">
            <div className="footer-left">
              <div>Contact: tomoki.sawai[at]outlook.com</div>
            </div>
            <div className="footer-right">
              <a href="https://github.com/polatria">
                <Image src={githubicon} alt={""} />
              </a>
            </div>
          </div>
        </div>
      </Html>
    </ImacModel>
  );
}
